### PR TITLE
move common logic to size-plugin-core & add support for size-plugin bot

### LINKED ISSUE #1: Share core functionality with size-plugin?
Hi @luwes!

I'm wondering if we should figure out a way to share the core size calculation and display logic between the two plugins so they can receive the same updates (in particular, GoogleChromeLabs/size-plugin#15). Thoughts?

### PR DESCRIPTION
**Pull request by kuldeepkeshwar**
I have created a [bot](https://github.com/kuldeepkeshwar/size-plugin-bot), which comments the sizes of the assets and the changes since the last build into the relevant PR

Support for the [bot](https://github.com/kuldeepkeshwar/size-plugin-bot) is already added to the webpack's [size-plugin](https://github.com/GoogleChromeLabs/size-plugin)  [here](https://github.com/GoogleChromeLabs/size-plugin/pull/21)

Summarizing the changes:
- move common logic to [size-plugin-core](https://github.com/kuldeepkeshwar/size-plugin-core)
- fixes #1
- add Bot link in README.md

### CODE REVIEW

**Review by luwes — DISMISSED** [review]
Awesome! LGTM

**Comment by luwes** [comment]
got an error npm linking this version.

Screen Shot 2019-08-25 at 12 18 01 PM

**Comment by kuldeepkeshwar** [comment]
@luwes it seems to work on my end. can you share the repo where you are trying?

**Comment by luwes** [comment]
@kuldeepkeshwar it's because `outputOptions.dir` is undefined on my end. In a lot of cases this will be the case I think, not everyone sets that in the rollup config. 

Maybe better go back to `path.dirname(outputOptions.file)`?

This is the repo: https://github.com/luwes/sinuous-todomvc

**Comment by luwes** [comment]
or maybe `output.dir || path.dirname(outputOptions.file)`?

**Comment by kuldeepkeshwar** [comment]
@luwes handled both cases(dir/file)

**Comment by luwes** [comment]
hmm, it's reading all the files in the dir. should only be the ones generated from rollup.

Screen Shot 2019-08-25 at 1 20 48 PM

**Comment by kuldeepkeshwar** [comment]
> hmm, it's reading all the files in the dir. should only be the ones generated from rollup.
> 
> Screen Shot 2019-08-25 at 1 20 48 PM

@luwes this is bit tricky, I will come back on it

**Comment by kuldeepkeshwar** [comment]
@luwes  you can use the `exclude` option to ignore files
```js
bundleSize({exclude:'!bundle.js'})
```

Note: delta not only includes the files which are created/updated in the current build but it also includes the files which are deleted in the current build & to do so plugin needs to consider all files in the directory to figure out which files are deleted in the current build.

**Comment by luwes** [comment]
very cool, will test this soon

**Comment by luwes** [comment]
@kuldeepkeshwar this looks good, only the output has to be only the current build.
they are build files in `/dist` so they can't be excluded but I only like to see the currently building file in the output.

what's the use case of wanting to see a fully deleted build file?

Screen Shot 2019-09-14 at 10 53 16 AM

**Comment by kuldeepkeshwar** [comment]
@luwes it should only show the delta(addition/modification/deletion).
If all those files are deleted in current build then they should come in delta.

Can you please share a repo link, I would like to dig it deeper

**Comment by kuldeepkeshwar** [comment]
@luwes help me close this.

**Comment by luwes** [comment]
@kuldeepkeshwar sorry for the late response. can I be of help to get the output issue fixed? it has to be included before we can merge this PR. it's the [luwes/sinuous](https://github.com/luwes/sinuous) repo.

**Comment by kuldeepkeshwar** [comment]
@luwes I have fixed it. Needed to handle the case of the single output file separately. 

Ref: 
Screen Shot 2019-10-05 at 1 42 26 AM

**Comment by luwes** [comment]
Awesome! almost there, could you just add these changes?

```diff
diff --git a/rollup-plugin-size.js b/rollup-plugin-size.js
index 839adc4..9afbf06 100644
--- a/rollup-plugin-size.js
+++ b/rollup-plugin-size.js
@@ -20,11 +20,11 @@ const defaults = {
  * @param {boolean} [options.publish] option to publish filesizes to size-plugin-store
  * @param {boolean} [options.writeFile] option to save filesizes to disk
  */
-function bundleSize(_options) {
-  const coreOptions = Object.assign(defaults, _options);
+function bundleSize(options) {
+  const coreOptions = Object.assign(defaults, options);
   coreOptions.compression = coreOptions.brotli ? 'brotli' : 'gzip';
 
-  const core = new SizePluginCore(_options);
+  const core = new SizePluginCore(coreOptions);
   async function generateBundle(outputOptions, bundle) {
     try {
       const assets = Object.keys(bundle).reduce((agg, key) => {
```

**Comment by luwes** [comment]
also on my end the newlines are too far apart. for a single output file it can be without an extra newline.

Screen Shot 2019-10-04 at 8 44 23 PM

**Comment by luwes** [comment]
could I also be added as maintainer to https://github.com/kuldeepkeshwar/size-plugin-core?

**Comment by kuldeepkeshwar** [comment]
@luwes updated the variable names.

Regarding the spacing, `size-plugin` uses this format & `rollup-plugin-size` has a different format (without extra newline character). we need to stick on one format. `size-plugin-core` was created by abstracting out functions from `size-plugin`.

> could I also be added as a maintainer to https://github.com/kuldeepkeshwar/size-plugin-core?

yes, just create a pull request. I will add you.

**Comment by luwes** [comment]
Awesome thanks! Great work 💪

**Pull request merged**
